/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guru.edu.sydrack.view;

import guru.edu.sydrack.converter.LocalDateAttributeConverter;
import guru.edu.sydrack.model.dao.EmployeeDAO;
import guru.edu.sydrack.model.dao.JobTitleDAO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sadrac
 */
public class ViewCadastrados extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastrados
     */
    public ViewCadastrados() {
        initComponents();
        readJTable();
        readCombox();
        panActions.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboxCargo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmp = new javax.swing.JTable();
        panActions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDataAdm = new javax.swing.JTextField();
        txtDataNasc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboxCargo2 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Cargo", "Idade", "Data de admissão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableEmp);

        jLabel1.setText("Id:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Data de nascimento:");

        jLabel4.setText("Data de admissão:");

        txtDataAdm.setText("dd/mm/aaaa");

        txtDataNasc.setText("dd/mm/aaaa");

        jLabel5.setText("Cargo:");

        javax.swing.GroupLayout panActionsLayout = new javax.swing.GroupLayout(panActions);
        panActions.setLayout(panActionsLayout);
        panActionsLayout.setHorizontalGroup(
            panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panActionsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panActionsLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addComponent(txtDataAdm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(comboxCargo2, 0, 311, Short.MAX_VALUE))
                .addContainerGap())
        );
        panActionsLayout.setVerticalGroup(
            panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panActionsLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(comboxCargo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuCadastrar.setText("Cadastrar novo funcionário");
        jMenuBar1.add(menuCadastrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void readJTable(){
        DefaultTableModel formatarTable = (DefaultTableModel) tableEmp.getModel();
        tableEmp.getColumnModel().getColumn(0).setPreferredWidth(20);
        tableEmp.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableEmp.getColumnModel().getColumn(2).setPreferredWidth(80);
        tableEmp.getColumnModel().getColumn(3).setPreferredWidth(20);
        tableEmp.getColumnModel().getColumn(4).setPreferredWidth(60);
        // Reseta a tabela
        formatarTable.setNumRows(0);
        EmployeeDAO eDAO = new EmployeeDAO();
        eDAO.findAll().forEach(e->{
           
            /*Date data = new Date();
            DateFormat dataFormatada = new SimpleDateFormat("Y");
            int anoAtual = Integer.parseInt(dataFormatada.format(data));
            int ano_nasc = e.getData_nascimento().getYear();
            System.out.println(ano_nasc);
            int idade = ano_nasc;
            System.out.println("  AQUI   "+idade);*/
            String dia = e.getData_admissao().toString().substring(8,10);
            String mes = e.getData_admissao().toString().substring(5,7);
            String ano = e.getData_admissao().toString().substring(0,4);
            String admissao = dia+"/"+mes+"/"+ano;
            formatarTable.addRow(new Object[]{
                e.getId(),
                e.getName(),
                e.getJob_title().getName(),
                idadeInteger(e.getData_nascimento()),
                admissao
            });
        });
    }
    public int idadeInteger(Date ano_nasc){
        int idade_quebrada = ano_nasc.getYear();
        int idade = 0;
        int anoNasc = 0;
        String idade_string = null;
        if(idade_quebrada < 100){
            idade_string = "19"+idade_quebrada;
            anoNasc = Integer.parseInt(idade_string);
        }else{
            idade_string = Integer.toString(idade_quebrada);
            String idade_string2 = idade_string.substring(1);
            idade_string = "20"+idade_string2;
            System.out.println(idade_string);
            anoNasc = Integer.parseInt(idade_string);
        }
         Date data = new Date();
         DateFormat dataFormatada = new SimpleDateFormat("Y");
         int anoAtual = Integer.parseInt(dataFormatada.format(data));
         idade = anoAtual-anoNasc;
        return idade;
    }
    public int admissInteger(Date ano_nasc){
        int idade_quebrada = ano_nasc.getYear();
        int idade = 0;
        int anoNasc = 0;
        String idade_string = null;
        if(idade_quebrada < 100){
            idade_string = "19"+idade_quebrada;
            anoNasc = Integer.parseInt(idade_string);
        }else{
            idade_string = Integer.toString(idade_quebrada);
            String idade_string2 = idade_string.substring(1);
            idade_string = "20"+idade_string2;
            System.out.println(idade_string);
            anoNasc = Integer.parseInt(idade_string);
        }
         Date data = new Date();
         DateFormat dataFormatada = new SimpleDateFormat("Y");
         int anoAtual = Integer.parseInt(dataFormatada.format(data));
         idade = anoAtual-anoNasc;
        return idade;
    }
    public void readCombox(){
        
        JobTitleDAO jtDAO = new JobTitleDAO();
        jtDAO.findAll().forEach(j -> {
            comboxCargo2.addItem(j.getName());
        });
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboxCargo;
    private javax.swing.JComboBox<String> comboxCargo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JPanel panActions;
    private javax.swing.JTable tableEmp;
    private javax.swing.JTextField txtDataAdm;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
